Repository cloudtty/cloudtty, pull requests merged in 2024-03, with the labels that each got.

#383 add template for commit a pr
  .github/PULL_REQUEST_TEMPLATE.md
Labels: good first issue, kind/feature, kind/doc

#387 Fix typos in the document
  README.md
  docs/keps/local-cluster-generate-kubeconfig.md
Labels: kind/documentation, lgtm

#393 feat: add golang-ci lint step
  .github/workflows/test-pr.yaml
  .golangci.yml
  pkg/apis/cloudshell/v1alpha1/types.go
  pkg/controllers/cloudshell_controller.go
  pkg/workerpool/queue.go
  pkg/workerpool/worker_pool.go
Labels: kind/feature
