Repository cloudtty/cloudtty, pull requests merged in 2024-06, with the labels that each got.

#435 Update OWNERS
  OWNERS
Labels: kind/documentation

#434 upgrade go verstion 1.21 to fix CVE-2024-24790
  docker/operator/Dockerfile
  go.mod
  go.sum
Labels: kind/bug, lgtm

#436 add panbin to cloudtty approver
  OWNERS
Labels: kind/documentation, lgtm
