Repository cloudtty/cloudtty, pull requests merged in 2024-04, with the labels that each got.

#397 fix the vulnerability in xz-libs, with the number CVE-2024-3094
  charts/cloudtty/Chart.yaml
  charts/cloudtty/readme.md
  charts/cloudtty/values.yaml
  docker/Dockerfile.example
  docker/cloudshell/Dockerfile
  pkg/constants/constants.go
Labels: kind/bug, lgtm

#399 cleanup root dir every time when starting cloudshell
  docker/cloudshell/script/startup.sh
Labels: kind/bug

#411 bump version to v0.7.2
  charts/cloudtty/Chart.yaml
  charts/cloudtty/readme.md
  charts/cloudtty/values.yaml
  docker/Dockerfile.example
  pkg/constants/constants.go
Labels: kind/cleanup

#412 feat: add gen helm doc in makefile
  Makefile
  charts/cloudtty/readme.md
  charts/cloudtty/values.yaml
Labels: kind/feature, lgtm

#413 add owners for project
  OWNERS
Labels: kind/cleanup
