Repository cloudtty/cloudtty, pull requests merged in 2025-03, with the labels that each got.

#568 fix reset.sh script exit 123
  docker/cloudshell/script/reset.sh
Labels: kind/bug

#566 Support setting custom annotations for ingress
  charts/cloudtty/_crds/cloudshell.cloudtty.io_cloudshells.yaml
  pkg/apis/cloudshell/v1alpha1/types.go
  pkg/apis/cloudshell/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/cloudshell_controller.go
  pkg/manifests/manifests.go
Labels: kind/feature, lgtm

#567 feat: Support setting font size
  docker/cloudshell/script/startup.sh
  pkg/controllers/cloudshell_controller.go
Labels: kind/feature, lgtm

#573 Fix cloudshell pod error when executing nslookup kubernetes.default
  docker/cloudshell/Dockerfile
Labels: kind/bug, lgtm

#574 feat: Support the client-options feature of ttyd
  charts/cloudtty/_crds/cloudshell.cloudtty.io_cloudshells.yaml
  docker/cloudshell/script/startup.sh
  pkg/apis/cloudshell/v1alpha1/types.go
  pkg/apis/cloudshell/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/cloudshell_controller.go
Labels: kind/feature, lgtm

#575 bump version to v0.8.5
  charts/cloudtty/Chart.yaml
  charts/cloudtty/readme.md
  charts/cloudtty/values.yaml
  docker/Dockerfile.example
  pkg/constants/constants.go
Labels: lgtm
